variable_netcdf_dir: '/ourdisk/hpc/ai2es/fronts/raw_front_data/era5-netcdf/'
domain: 'full'
model_dir: "/ourdisk/hpc/ai2es/tman/models/"
model_number: 27998912
data_source: 'era5'
init_time: '2024-01-26-00'
gpu_device: 0