era5_config:
  era5_uri: "gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3"
  variables: ["geopotential", "temperature", "u_component_of_wind", "v_component_of_wind", "specific_humidity", "vertical_velocity"]
  pressure_levels: [1000, 925, 850, 700, 500, 300]
  time_start: "2018-01-01T00:00:00"
  time_end: "2024-12-31T23:59:00"
  time_resolution: "6h"
  coordinates: [0.25, 80, 130, 369.75]
  storage_options: {"token": "anon"}
  chunks: {"time": 1, "level": -1, "latitude": -1, "longitude": -1}

icechunk_storage_config:
  store_path: "/ourdisk/hpc/ai2es/tman/data/fronts/train/icechunk/"
  branch_name: "main"
  commit_message: "Add raw ERA5 data for 2018-2024"



